<?php

use App\Constants\Gender;
use App\Constants\QuestionType;
use App\Constants\Religion;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->truncate();
        $questions = [

            [
                // 'id'=>1,
                'content' => 'ما طولك؟',
                'category_id' => '1',
                'type' => QuestionType::DIGITAL,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>2,
                'content' => 'ما وزنك',
                'category_id' => '1',
                'type' => QuestionType::DIGITAL,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                // 'id'=3,
                'content' => 'ما لون بشرتك؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>4,
                'content' => 'هل تمارس الرياضة؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                // 'id'=>5,
                'content' => 'هل تمارسين الرياضة؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                // 'id'=>6,
                'content' => 'ما ھى إھتماماتك ؟',
                'category_id' => '1',
                'type' => QuestionType::MULTIPLE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                // 'id'=>7,
                'content' => 'بلد إقامتك ؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>8,
                'content' => 'محافظة إقامتك ؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>9,
                'content' => 'منطقة إقامتك ؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>10,
                'content' => 'منطقة إقامتك ؟',
                'category_id' => '1',
                'type' => QuestionType::TEXT,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],

            [
                // 'id'=>11,
                'content' => 'نوع شقة الزواج؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>12,
                'content' => 'بلد شقة الزواج؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>13,
                'content' => 'محافظة شقة الزواج ؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>14,
                'content' => 'منطقة شقة الزواج؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>15,
                'content' => 'منطقة شقة الزواج؟',
                'category_id' => '1',
                'type' => QuestionType::TEXT,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>16,
                'content' => 'مساحة شقة الزواج؟',
                'category_id' => '1',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            // ----------------------------------
            // 2- الدين والحالة الاجتماعية

            [
                 // 'id'=>17,
                'content' => 'الحالة الإجتماعیة ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],

            [
                 // 'id'=>18,
                'content' => 'الحالة الإجتماعیة ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>19,
                'content' => 'منذ متى وفاة الزوجة ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>20,
                'content' => 'منذ متى وفاة الزوج ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>21,
                'content' => 'منذ متى الطلاق ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>22,
                'content' => ' كم عدد زوجاتك الحالیین ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>23,
                'content' => ' ھل لدیك أولاد ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>24,
                'content' => ' عدد أولادك الذكور ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>25,
                'content' => ' عدد أولادك الإناث ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>26,
                'content' => 'عمر أكبر أولادك ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>27,
                'content' => 'ھل أولادك یعیشون معك ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>28,
                'content' => 'ھل ترغب بإنجاب الأطفال من زواجك القادم ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                // 'id'=>29,
                'content' => 'أسعى للزواج خلال ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                // 'id'=>30,
                'content' => 'طائفتك ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::CHRESTIAN,
                'can_skip' => true,
            ],
            [
                 // 'id'=>31,
                'content' => 'الصلاة ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::MUSLIM,
                'can_skip' => true,
            ],
            [
                 // 'id'=>32,
                'content' => 'الصلاة فى المسجد ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::MUSLIM,
                'can_skip' => true,
            ],
            [
                 // 'id'=>33,
                'content' => 'الصيام ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::MUSLIM,
                'can_skip' => true,
            ],
            [
                 // 'id'=>34,
                'content' => 'التدخين ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                 // 'id'=>35,
                'content' => 'الحجاب ؟',
                'category_id' => '2',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::MUSLIM,
                'can_skip' => false,
            ],

// -------------- التعليم والعمل 3
            [
                 // 'id'=>36,
                'content' => 'مؤھلك الدراسى ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                 // 'id'=>37,
                'content' => 'الجامعة ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                 // 'id'=>38,
                'content' => 'الكلیة ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                 // 'id'=>39,
                'content' => 'سنة إنھاء الدراسة ؟',
                'category_id' => '3',
                'type' => QuestionType::DIGITAL,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                 // 'id'=>40,
                'content' => 'عملك ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                 // 'id'=>41,
                'content' => 'عملك ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::FEMALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'بلد عملك ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'وصف طبیعة عملك ؟',
                'category_id' => '3',
                'type' => QuestionType::TEXT,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                'content' => 'الإستقرار فى العمل ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                'content' => 'ھل تبحث عن مجال عمل آخر ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                'content' => 'مدة بقائك فى عملك الحالى ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],
            [
                'content' => 'ھل تمتلك سیارة خاصة ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'ھل تریدین العمل بعد الزواج ؟',
                'category_id' => '3',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::MALE,
                'religion' => Religion::ALL,
                'can_skip' => true,
            ],

            // ----------- 4- العائلة
            [
                'content' => 'الوالد ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'عمل الوالد ؟',
                'category_id' => '4',
                'type' => QuestionType::TEXT,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'الوالدة ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'عمل الوالدة ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'عدد إخوتك الذكور ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'عدد إخوتك الإناث ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'ترتیبك بین إخوتك ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],
            [
                'content' => 'مستوى العائلة ؟',
                'category_id' => '4',
                'type' => QuestionType::ONE_CHOICE,
                'gender' => Gender::ALL,
                'religion' => Religion::ALL,
                'can_skip' => false,
            ],

        ];

        DB::table('questions')->insert($questions);
    }
}
