<?php

namespace App\Constants;

 class Points {

    CONST PARENT_INFO = 35;     // USER REQUEST TO SHOW PARENT INFO
    CONST FILTER_WEEK = 45;     // USER REQUEST TO SHOW FILTER FOR A WEEK
    CONST FILTER_TWO_WEEK = 80; // USER REQUEST TO SHOW FILTER FOR TWO WEEKS
    CONST GIRL_SHARING = 25;    // EVERY TIME GIRL SHARE THE APP
    CONST MINIMUM_POINTS_FOR_CHARGE = 40; // MINIMUM POINTS USER CAN BUY
}
